image: 636081672552.dkr.ecr.eu-north-1.amazonaws.com/dp-full:v1


vscode:
  extensions:
    - ms-python.python # Python
    - ms-python.vscode-pylance # Pylance
    - ms-toolsai.jupyter # Jupyter support
    - tamasfe.even-better-toml # Even Better TOML
